### ISSUE TITLE
Remove `*sudo* pip install` from the tutorial

### ISSUE THREAD

**Issue by leliel12** [lindonroberts/trust-region#6]
The tutorial says

![imagen](https://github.com/user-attachments/assets/bb8e945d-56e5-41be-b3f8-2f2c79991dda)

This is an extremely dangerous advice, you can brick an entire system.

A more detailed explanations:

- https://askubuntu.com/questions/802544/is-sudo-pip-install-still-a-broken-practice.

Please suggest alternatives like:

- https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/
- https://virtualenv.pypa.io/en/latest/
- Or install pip inside a [conda](https://anaconda.org/anaconda/conda)  environment and then install trust-region.

**Comment by lindonroberts** [comment]
Thanks, good idea!
