### ISSUE TITLE
If I have a Jacobian matrix how can I use this package?

### ISSUE THREAD

**Issue by xichaoqiang** [lindonroberts/trust-region#7]
If I have a Jacobian matrix how can I use this package?

**Comment by lindonroberts** [comment]
It depends on what the Jacobian matrix is for. Two common situations are:

Constrained optimization: if you have constraints like $c(x)=0$ or $c(x)\geq 0$, then the Jacobian $J(x)$ contains the derivatives of each component of $c$ with respect to each component of $x$. This package doesn't solve this type of problem.

Nonlinear least-squares optimization: if you problem is of the form $\min_{x} f(x) = \frac{1}{2}\sum_{i} r_i(x)^2$, then the Jacobian $J(x)$ contains the derivatives of each $r_i$ with respect to each component of $x$. In that case, this package can be used with $g=J(x)^T r(x)$ and $H=J(x)^T J(x)$ to implement the Gauss-Newton method, for example.

**Comment by xichaoqiang** [comment]
How can I set weight to get the x smoother?

**Comment by lindonroberts** [comment]
I'm not sure what you mean. Here, $x$ is a vector, and 'smooth' isn't a usual way to describe a vector. If you are solving a data fitting problem, then $x$ might represent parameters of a function, so you may want the fitting function to be smooth? In that case, you could look at [regularization](https://www.ibm.com/topics/regularization) of your optimization problem as a way to do this. 

The trustregion package cannot help with formulating the optimization problem. It is a tool to assist people who are writing their own optimization algorithms.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
